# Page language (html attribute)
language: en

# Main menu navigation items
menu:
  Blog: /
  About: /about
  Archives: /archives

# Post social sharing features
social:
  twitter: your_twitter # set to your twitter handle

# Page sidebars
# Components will appear in the order they are specified
sidebars:
  recent: true # boolean to display 10 most recent posts
  featured: false # boolean to list all posts with tag 'featured'
  github: your_github # string to point to a Github profile | false to disable

# Link to atom.xml in nav bar?
# You can use https://github.com/hexojs/hexo-generator-feed to generate these
atom: true

# Stylesheets loaded in the <head>
stylesheets:

# Scripts loaded at the end of the body
scripts:
